"""Shared hardware / imaging constants for main and GUI."""

IMAGING_ROWS = 8
IMAGING_COLS = 8
CAMERA_STEPSIZE = 95
PETRI_STEPSIZE = 76

PETRI_DISH_PRE_UP = 740
CAMERA_DISH_PRE_UP = 3730
PETRI_DISH_PRE_UP_ROW2 = 1460
CAMERA_DISH_PRE_UP_ROW2 = 3750

PETRI_TRAY_ROWS = 2
PETRI_TRAY_COLS = 5
MAX_PETRI_DISHES = PETRI_TRAY_ROWS * PETRI_TRAY_COLS

# Steps panel — quick incubation (Start Incubation button)
STEP_INCUBATION_TEMP_C = 37.0
STEP_INCUBATION_MINUTES = 2.0

# Incubation + imaging study — up to 10 rounds (temp + time each)
NUM_STUDY_ROUNDS = 10
INCUBATION_TEMP_MIN = 20.0
INCUBATION_TEMP_MAX = 55.0
INCUBATION_TEMP_STEP = 1.0
DEFAULT_ROUND_TEMPS = (37.0,) * NUM_STUDY_ROUNDS
DEFAULT_ROUND_TIMES_MIN = (4.0,) * NUM_STUDY_ROUNDS
DEFAULT_ROUND_ENABLED = (True,) + (False,) * (NUM_STUDY_ROUNDS - 1)
INCUBATION_MIN_STEP = 0.5
INCUBATION_MIN_MIN = 0.5
INCUBATION_MIN_MAX = 600.0
INCUBATION_HOUR_STEP = 0.25

# Split imaging (10 dishes): row-1 capture → home → mid incubation → row-2 capture
MID_ROW_IMAGING_TEMP_C = 37.0
MID_ROW_IMAGING_MIN = 4.0
DISHES_PER_TRAY_ROW = PETRI_TRAY_COLS

# Camera disconnect during imaging: all home → incubate → retry the failed dish
CAMERA_DISCONNECT_RECOVERY_TEMP_C = 37.0
CAMERA_DISCONNECT_RECOVERY_MIN = 5.0
CAMERA_DISCONNECT_MAX_RECOVERIES = 5

# Legacy aliases (workflow / imports)
NUM_INCUBATION_SLOTS = 3
NUM_PICTURE_SLOTS = NUM_STUDY_ROUNDS
